### ISSUE TITLE
npm ci && ng build --prod - Error: Cannot find module 'node-sass'

### ISSUE THREAD

**Issue by dharmjit** [trion-development/docker-ng-cli#10]
Hi, we have been using this docker image in our CICD process for quite some time now and it was working fine. From last few days suddenly we are seeing below error in below steps.

Initially the error is in **npm ci** step and we tried changing the image tag to 8.3.12 and **npm ci** error got resolved and has moved to ng build step

```
npm ci
ng build --prod

Error: Cannot find module 'node-sass'```

**Comment by everflux** [comment]
Thank you for opening this issue.
Could you please try if  using npm install instead of ci solves the problem?
On which platform are you building ?

**Comment by codecoster** [comment]
Hi @dharmjit !
Unfortunately we could not reproduce your issue.
Could you please provide a way to reproduce your problem?

**Comment by everflux** [comment]
Could this question be related? https://stackoverflow.com/questions/58660939/yarn-build-with-webpack-inconsistency-in-gitlab

**Comment by everflux** [comment]
I can not reproduce the issue - please reopen if you can provide more information.
