### ISSUE TITLE
Readme needs an update

### ISSUE THREAD

**Issue by will-l-h** [trion-development/docker-ng-cli#11]
The readme says 
`Currently this image uses node 9 (npm 5) and Debian stretch as base distribution.`

But it's based on node:lts-slim which is node 12. I was thrown for a second on how this might be working since angular 8 requires node 10 or later.

**Comment by everflux** [comment]
Oh that is right - sorry about that. If you like please open a pull request ;)

**Comment by will-l-h** [comment]
Done.
https://github.com/trion-development/docker-ng-cli/pull/12
