### ISSUE TITLE
Add curl

### ISSUE THREAD

**Issue by nickroberts** [trion-development/docker-ng-cli#15]
What are the possibilities of adding the `curl` utility to this image?

We use it to upload and download artifacts to our internal repository. I know you already added the `zip` utility (thank you!), and this would make things even better.

We actually use the `ng-cli-e2e` image, but since this is the base image, it would get added there, as well.

I can create an image off of yours, but it would be nice if this was added here, instead.

I can also create a pull request to this repo, if you'd like.

Thanks, and keep up the great work!

**Comment by everflux** [comment]
Thanks a lot for the PR!

Merged and will be part of 9.0.6 when available.
