### ISSUE TITLE
node lts is now 14.15.1 

### ISSUE THREAD

**Issue by param-artha** [trion-development/docker-ng-cli#19]
Since node LTS is 14.15.1 this image is no longer nodejs 12 npm 6. Would it be possible to update the image to use node 12-slim or similar? 

Our build is failing because of a dependency "node-sass" build errors. Aparently node-sass doesn't support node 14.15.1.

**Comment by codecoster** [comment]
Node-Sass should support Node 14 (https://github.com/sass/node-sass/issues/2895)
Could you please try:
1) Install node 14 locally
2) Delete node-modules/package-lock.json
3) npm install

**Comment by param-artha** [comment]
Thanks! We ended up having to update most of the packages (node-sass, fsevents, grpc, firebase etc) to support LTS :)

**Comment by everflux** [comment]
We are happy this worked out for you! 
On the long run it is better to update very now and then instead of waiting until the app is beyond expiration ;)

I will close the issue please reopen if we forgot an important aspect.
