### ISSUE TITLE
Use aggregated tags

### ISSUE THREAD

**Issue by logoff** [trion-development/docker-ng-cli#20]
Hi.

I like using this image for my local development and CI pipelines!

I would like to have aggregated tags in Docker Hub, so images may be referenced using only major or minor version parts.

Example: tag 11 should refer to most modern version of 11.x, and tag 10.0 should refer to most modern version of 10.0.x.

Many other project use this schema.

Thanks.

**Comment by Gogistics** [comment]
Hello,
Help yourself and have fun

**Comment by everflux** [comment]
Thank you for taking the time to provide feedback to this project.
I would like to understand your use case a little better before implementing the proposed tagging workflow.

Are you using different versions of the image in your CI build to verify that your application builds with multiple versions?
We recommend to our customers to move to the latest version as soon as feasible and the CLI image is usually able to be used with an older version of the Angular CLI. Currently I don't see the use case for tagging the major versions separately.

**Comment by logoff** [comment]
Hello!

I'd like to build with an exact version like development to avoid unaligned results. Example, a project developed using Angular 10.X and built with the latest available version of Angular CLI in 10.X.

Thanks.

**Comment by everflux** [comment]
For the exact-version use case we tag the images with the exact version of the Angular CLI bundled in the image.
Please note that the current Angular CLI uses the version specified in the package.json anyway, so no need to have the exact image version.
