### ISSUE TITLE
Mounting - issues

### ISSUE THREAD

**Issue by KR-Ravindra** [trion-development/docker-ng-cli#23]
When we mount any file to this docker image they are being wirtten as 1003 user.. but i guess only node has permission to write over here.. so 1003 npm i fails

**Comment by everflux** [comment]
Could you show how you are using the image?

**Comment by KR-Ravindra** [comment]
Yeah, I have the following couple of screenshots.

A bit of context: On left I have mounted files from host, on right I have used git clone to copy the code of frontend application.

In Screenshot1: 

We see, the mounted part gets a different ownership and group ID ( Well! as expected because its docker! ), so my "npm i" fails due to permission issue, to use chown... I am unaware of this root password (if any exists).

![Screenshot_20210624_102630](https://user-images.githubusercontent.com/42912207/123205285-38be8800-d4d7-11eb-904a-acc99b91df0e.png)

In the Screenshot2:

Here I am trying to run the "npm i" as expected the left is going to fail and the right is going to succeed.
I did try to modify this dockerfile availble over [here](https://hub.docker.com/r/trion/ng-cli/dockerfile). It didnt workout for me. 

![Screenshot_20210624_102758](https://user-images.githubusercontent.com/42912207/123205448-8d620300-d4d7-11eb-8d64-edc0f96e4fba.png)

Similar issue is active over [here](https://github.com/moby/moby/issues/2259)
Any help?

**Comment by everflux** [comment]
I wonder why you are calling the docker cli as root (`sudo docker...`). This gives me the impression that your docker setup is not fully performed.
A quick fix could be to tell docker running the container with your use rid:
`docker run -u 1003 ...`
Another option would be to make your directory world-writeable.
