### ISSUE TITLE
Image should support yarn

### ISSUE THREAD

**Issue by grueny** [trion-development/docker-ng-cli#4]
- [x] feature request

Now we have to add yarn by ourselves. 

## Desired functionality
We would like to use a preinstalled yarn in the pipeline.

**Comment by everflux** [comment]
Added yarn support an according documentation. Please test docker file from GH-4 branch and let me know, if it works for you.

**Comment by grueny** [comment]
yarn has not the right to write to /tmp/.cache/yarn/v1 because it belongs to root. Here is the exception: 
`yarn install v0.24.5
error An unexpected error occurred: "EACCES: permission denied, mkdir '/tmp/.cache/yarn/v1'".
`
I used the following command:
docker run -u $(id -u) --rm -v "$PWD/../yarn-cache":/tmp/.cache/yarn -v "$PWD":/app tri
on/ng-cli:GH-4_add_yarn_support yarn install

**Comment by everflux** [comment]
Do you have a directory "yarn-cache" on a directory above your angular project with sufficient access rights? If you have used yarn locally (outside docker) before, please try this instead:

```
docker run -u $(id -u) --rm -v "$HOME/.cache/yarn":/tmp/.cache/yarn -v "$PWD":/app trion/ng-cli sh -c "ng set --global packageManager=yarn; ng new MyDemoProject"
```

**Comment by everflux** [comment]
Merged into master and available in latest images. Reopen or file a new ticket, if the issue persists.
