### ISSUE TITLE
Unable to install ssh agent after package change

### ISSUE THREAD

**Issue by patrickml** [trion-development/docker-ng-cli#7]
We noticed our builds started to fail after doing some research it looks like the base image for this package was recently changed. This change has made it so we cannot install ssh-agent onto the machine.

```
$ which ssh-agent || ( apt-get update -y && apt-get install openssh-clients -y )
Hit:1 http://security.debian.org/debian-security stretch/updates InRelease
Ign:2 http://deb.debian.org/debian stretch InRelease
Hit:3 http://deb.debian.org/debian stretch-updates InRelease
Hit:4 http://deb.debian.org/debian stretch Release
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package openssh-clients
ERROR: Job failed: exit code 1
```

**Comment by everflux** [comment]
Thanks for opening an issue.
I believe that in your case there is a typo, the package should read "openssh-client".

Besides what is the use case to install an ssh-agent inside the image? If you want to distribute the build artifact I suggest to switch the image to a different one for that step - this speeds up the build process ( no installation necessary for each build) and helps to separate the concerns of building and deployment to separate images.
