### ISSUE TITLE
Node version

### ISSUE THREAD

**Issue by mackelito** [trion-development/docker-ng-cli#9]
Just wondering if you might consider changing from node:lts-slim to something with a newer node version? :)

**Comment by everflux** [comment]
Which node version would you prefer? What is the requirement to have a newer version of node available/what benefit would it provide over LTS?

**Comment by mackelito** [comment]
When we use an older version of node we get memory errors `FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`

But when running node 12 it works fine... guess there are improvements to memory usage. :)

**Comment by mackelito** [comment]
We are using a workaround where we use `node --max_old_space_size=3072 node_modules/@angular/cli/bin/ng build --prod --configuration=production` and that works so there no critical need..

What are the benefits of not running node 12?
(v12 will have a "Active LTS Start" on 2019-10-22 so there are just a few days left 😁)

**Comment by everflux** [comment]
Under what conditions are you observing the issue? Is it during project build or test execution? Is it an ionic project or plain angular?

**Comment by mackelito** [comment]
this is when building --prod.. a plain angular project.
There are several github issues on this topic :)

https://github.com/angular/angular-cli/issues/13734
https://github.com/angular/angular-cli/issues/15242
https://github.com/angular/angular-cli/issues/9157

**Comment by everflux** [comment]
Did you try to set this environment
`NODE_OPTIONS=--max_old_space_size=4096` (or even 8192) 
or use a custom build command to increase the the available memory?

```
"scripts": {
        "start": "node --max-old-space-size=4096 ./node_modules/@angular/cli/bin/ng serve",
        "build:prod": "node --max-old-space-size=4096 ./node_modules/@angular/cli/bin/ng build --prod",
}
```

Some commenters reported that using Angular CLI of at least 8.2.6 solved their memory problem - is that the case with your project as well?

**Comment by everflux** [comment]
Additional notes:
If you are running docker on Windows or Mac you might need to configure the docker VM to provide enough memory as well.

Node 12 will become LTS as of 2019-10-21 - the next image build after that date will therefore upgrade node.js automatically.

**Comment by mackelito** [comment]
@everflux as stated earlier, yes we do use this workaround.. 
We are using CLI version 8.3.6
Our CI is an unix gitlab runner with 3GB ram if I remember correctly :)

**Comment by everflux** [comment]
sorey didn’t recollect your comment when writing the proposed work around. 
I will leave this issue open until the lts node version is bumped to 12 which should be rather soon. 

Thanks for getting in touch and your feedback!

**Comment by mackelito** [comment]
Just realised that we had bigger issues using this image 😂
we have several issues similar to this one:
`npm WARN checkPermissions Missing write access to /builds/node_modules/@angular-devkit/architect/node_modules/tslib`

edit: We also tried to run using `npm install --unsafe-perm`

**Comment by everflux** [comment]
Node 12 is now LTS and in latest and 8.3.13 images.

Please open a separate issue if you encounter different problems or have improvement suggestions, thank you!
